[package]
name = "nvim-gtk"
version = "0.1.2"
authors = ["daa84 <daa84@inbox.ru>"]
build = "build.rs"

[dependencies]
#cairo-rs = "0.1"
#pango = "0.1"
#pangocairo = "0.1"
#glib = "0.1"
#glib-sys = "0.3"
#gdk = "0.5"
#gdk-sys = "0.3"
#gio = "0.1"
gdk = { git = 'https://github.com/gtk-rs/gdk' }
gdk-sys = { git = 'https://github.com/gtk-rs/sys' }
glib = { git = 'https://github.com/gtk-rs/glib' }
glib-sys = { git = 'https://github.com/gtk-rs/sys' }
cairo-rs = { git = 'https://github.com/gtk-rs/cairo' }
cairo-sys-rs = { git = 'https://github.com/gtk-rs/cairo' }
pango = { git = 'https://github.com/gtk-rs/pango' }
pango-sys = { git = 'https://github.com/gtk-rs/sys' }
gio = { git = 'https://github.com/gtk-rs/gio' }
pangocairo = { git = 'https://github.com/RazrFalcon/pangocairo-rs' }
neovim-lib = "0.4"
phf = "0.7"
log = "0.3"
env_logger = "0.4"
htmlescape = "0.3"

serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

#[dependencies.neovim-lib]
#git = "https://github.com/daa84/neovim-lib"

[build-dependencies]
phf_codegen = "0.7"

[dependencies.gtk]
version = "0.1"
features = ["v3_22"]
git = "https://github.com/daa84/gtk"

[dependencies.gtk-sys]
version = "0.3"
features = ["v3_22"]
git = 'https://github.com/gtk-rs/sys'

[replace]
"gdk:0.5.3" = { git = 'https://github.com/gtk-rs/gdk' }
"gdk-sys:0.3.4" = { git = 'https://github.com/gtk-rs/sys' }
"glib:0.1.3" = { git = 'https://github.com/gtk-rs/glib' }
"glib-sys:0.3.4" = { git = 'https://github.com/gtk-rs/sys' }
"cairo-rs:0.1.3" = { git = 'https://github.com/gtk-rs/cairo' }
"cairo-sys-rs:0.3.4" = { git = 'https://github.com/gtk-rs/cairo' }
"pango:0.1.3" = { git = 'https://github.com/gtk-rs/pango' }
"pango-sys:0.3.4" = { git = 'https://github.com/gtk-rs/sys' }
"gtk-sys:0.3.4" = { git = 'https://github.com/gtk-rs/sys' }
"gio:0.1.3" = { git = 'https://github.com/gtk-rs/gio' }
