[package]
name = "neovim-gtk"
version = "0.1.1"
authors = ["daa84 <daa84@inbox.ru>"]
build = "build.rs"

[dependencies]
cairo-rs = "0.1"
pangocairo = "0.1"
glib = "0.1"
glib-sys = "0.3"
gdk = "0.5"
gdk-sys = "0.3"
#neovim-lib = "^0.1.1"
phf = "0.7"

[dependencies.neovim-lib]
git = "https://github.com/daa84/neovim-lib"

[build-dependencies]
phf_codegen = "0.7"

[dependencies.gtk]
version = "0.1"
features = ["v3_10"]

