[package]
name = "neovim-gtk"
version = "0.1.0"
authors = ["daa84 <daa84@inbox.ru>"]
build = "build.rs"

[dependencies]
cairo-rs = "0.0.8"
glib = "0.0.8"
#neovim-lib = "0.1"
rmp = "0.7"

[dependencies.neovim-lib]
path = "../neovim-lib/"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_10"]

